param()

$ErrorActionPreference = "Stop"
[Console]::InputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $projectRoot

function Read-Value {
    param(
        [string]$Prompt,
        [string]$Default = "",
        [switch]$Secret
    )

    if ($Secret) {
        $secure = Read-Host -Prompt $Prompt -AsSecureString
        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
        try {
            $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
        }
        finally {
            if ($bstr -ne [IntPtr]::Zero) {
                [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
            }
        }
        if ([string]::IsNullOrWhiteSpace($plain)) {
            return $Default
        }
        return $plain
    }

    $suffix = ""
    if (-not [string]::IsNullOrWhiteSpace($Default)) {
        $suffix = " [$Default]"
    }
    $value = Read-Host "$Prompt$suffix"
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }
    return $value.Trim()
}

function Select-Option {
    param(
        [string]$Title,
        [string[]]$Options,
        [int]$DefaultIndex = 1
    )

    Write-Host ""
    Write-Host $Title -ForegroundColor Cyan
    for ($i = 0; $i -lt $Options.Count; $i++) {
        Write-Host ("[{0}] {1}" -f ($i + 1), $Options[$i])
    }

    while ($true) {
        $choice = Read-Host ("Choose number [{0}]" -f $DefaultIndex)
        if ([string]::IsNullOrWhiteSpace($choice)) {
            $choice = [string]$DefaultIndex
        }
        if ($choice -match '^\d+$') {
            $index = [int]$choice
            if ($index -ge 1 -and $index -le $Options.Count) {
                return $index
            }
        }
        Write-Host "Invalid choice. Try again." -ForegroundColor Yellow
    }
}

function Get-DefaultIndex {
    param(
        [string[]]$Options,
        [string]$CurrentValue,
        [int]$Fallback = 1
    )

    for ($i = 0; $i -lt $Options.Count; $i++) {
        if ($Options[$i] -eq $CurrentValue) {
            return $i + 1
        }
    }
    return $Fallback
}

function Load-EnvMap {
    param([string]$Path)

    $envMap = @{}
    if (-not (Test-Path $Path)) {
        return $envMap
    }

    foreach ($line in Get-Content $Path -Encoding UTF8) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#") -or -not $trimmed.Contains("=")) {
            continue
        }
        $pair = $trimmed.Split("=", 2)
        $envMap[$pair[0].Trim()] = $pair[1].Trim()
    }
    return $envMap
}

function Save-EnvFile {
    param(
        [string]$Path,
        [hashtable]$Values
    )

    $content = @(
        "# Generated by start.ps1"
        "DEEPSEEK_API_KEY=$($Values.DEEPSEEK_API_KEY)"
        "DEEPSEEK_BASE_URL=$($Values.DEEPSEEK_BASE_URL)"
        "DEEPSEEK_CHAT_MODEL=$($Values.DEEPSEEK_CHAT_MODEL)"
        "DEEPSEEK_REASONER_MODEL=$($Values.DEEPSEEK_REASONER_MODEL)"
        ""
        "# OCR (optional)"
        "DEEPSEEK_OCR_BASE_URL=$($Values.DEEPSEEK_OCR_BASE_URL)"
        "DEEPSEEK_OCR_MODEL=$($Values.DEEPSEEK_OCR_MODEL)"
        ""
        "# Vector store config"
        "VECTOR_STORE=$($Values.VECTOR_STORE)"
        "CASE_INDEX_DIR=$($Values.CASE_INDEX_DIR)"
    ) -join "`r`n"

    [System.IO.File]::WriteAllText($Path, $content, [System.Text.UTF8Encoding]::new($false))
}

function Export-EnvVars {
    param([hashtable]$Values)

    foreach ($item in $Values.GetEnumerator()) {
        [System.Environment]::SetEnvironmentVariable($item.Key, [string]$item.Value, "Process")
    }
}

$envPath = Join-Path $projectRoot ".env"
$existing = Load-EnvMap -Path $envPath

$chatOptions = @(
    "deepseek-chat",
    "deepseek-reasoner",
    "gpt-4o-mini",
    "gpt-4.1-mini",
    "custom"
)
$reasonerOptions = @(
    "deepseek-reasoner",
    "deepseek-chat",
    "o3-mini",
    "gpt-5-mini",
    "custom"
)
$runOptions = @(
    "Streamlit UI (recommended)",
    "CLI demo",
    "FastAPI server"
)

$defaultApiKey = $existing["DEEPSEEK_API_KEY"]
$defaultBaseUrl = if ($existing["DEEPSEEK_BASE_URL"]) { $existing["DEEPSEEK_BASE_URL"] } else { "https://api.deepseek.com/v1" }
$defaultChatModel = if ($existing["DEEPSEEK_CHAT_MODEL"]) { $existing["DEEPSEEK_CHAT_MODEL"] } else { "deepseek-chat" }
$defaultReasonerModel = if ($existing["DEEPSEEK_REASONER_MODEL"]) { $existing["DEEPSEEK_REASONER_MODEL"] } else { "deepseek-reasoner" }
$defaultOcrBaseUrl = if ($existing["DEEPSEEK_OCR_BASE_URL"]) { $existing["DEEPSEEK_OCR_BASE_URL"] } else { "http://localhost:8000/v1" }
$defaultOcrModel = if ($existing["DEEPSEEK_OCR_MODEL"]) { $existing["DEEPSEEK_OCR_MODEL"] } else { "deepseek-ai/DeepSeek-OCR" }
$defaultVectorStore = if ($existing["VECTOR_STORE"]) { $existing["VECTOR_STORE"] } else { "faiss" }
$defaultIndexDir = if ($existing["CASE_INDEX_DIR"]) { $existing["CASE_INDEX_DIR"] } else { "outputs/cases/index" }

$defaultChatIndex = Get-DefaultIndex -Options $chatOptions -CurrentValue $defaultChatModel -Fallback 1
$defaultReasonerIndex = Get-DefaultIndex -Options $reasonerOptions -CurrentValue $defaultReasonerModel -Fallback 1

Write-Host ""
Write-Host "Startup Edu Agent launcher" -ForegroundColor Green
Write-Host "Project root: $projectRoot"
Write-Host "UI flow: login -> Student / Teacher / Admin / Function Center" -ForegroundColor DarkGray
Write-Host "Mock student: student / student123" -ForegroundColor DarkGray
Write-Host "Mock teacher: teacher / teacher123" -ForegroundColor DarkGray
Write-Host "Mock admin: admin / admin123" -ForegroundColor DarkGray

$installChoice = Select-Option -Title "Install or update dependencies first?" -Options @("Yes (recommended)", "No") -DefaultIndex 1
if ($installChoice -eq 1) {
    & py -3.11 -m pip install -e ".[test,ocr,ui]"
}

Write-Host ""
Write-Host "Configure API and models" -ForegroundColor Cyan
$apiKey = Read-Value -Prompt "API key (blank keeps current value / allows offline fallback)" -Default $defaultApiKey -Secret
$baseUrl = Read-Value -Prompt "API base URL" -Default $defaultBaseUrl

$chatChoice = Select-Option -Title "Select chat model" -Options $chatOptions -DefaultIndex $defaultChatIndex
$chatModel = $chatOptions[$chatChoice - 1]
if ($chatModel -eq "custom") {
    $chatModel = Read-Value -Prompt "Custom chat model" -Default $defaultChatModel
}

$reasonerChoice = Select-Option -Title "Select reasoning model" -Options $reasonerOptions -DefaultIndex $defaultReasonerIndex
$reasonerModel = $reasonerOptions[$reasonerChoice - 1]
if ($reasonerModel -eq "custom") {
    $reasonerModel = Read-Value -Prompt "Custom reasoning model" -Default $defaultReasonerModel
}

$ocrBaseUrl = Read-Value -Prompt "OCR base URL" -Default $defaultOcrBaseUrl
$ocrModel = Read-Value -Prompt "OCR model" -Default $defaultOcrModel

$envValues = @{
    DEEPSEEK_API_KEY = $apiKey
    DEEPSEEK_BASE_URL = $baseUrl
    DEEPSEEK_CHAT_MODEL = $chatModel
    DEEPSEEK_REASONER_MODEL = $reasonerModel
    DEEPSEEK_OCR_BASE_URL = $ocrBaseUrl
    DEEPSEEK_OCR_MODEL = $ocrModel
    VECTOR_STORE = $defaultVectorStore
    CASE_INDEX_DIR = $defaultIndexDir
}

Save-EnvFile -Path $envPath -Values $envValues
Export-EnvVars -Values $envValues

Write-Host ""
Write-Host ".env updated:" -ForegroundColor Green
Write-Host "  DEEPSEEK_BASE_URL=$baseUrl"
Write-Host "  DEEPSEEK_CHAT_MODEL=$chatModel"
Write-Host "  DEEPSEEK_REASONER_MODEL=$reasonerModel"
Write-Host "  DEEPSEEK_OCR_BASE_URL=$ocrBaseUrl"
Write-Host "  DEEPSEEK_OCR_MODEL=$ocrModel"

$runChoice = Select-Option -Title "Choose startup mode" -Options $runOptions -DefaultIndex 1

switch ($runChoice) {
    1 {
        Write-Host ""
        Write-Host "Launching Streamlit UI..." -ForegroundColor Green
        Write-Host "Open the browser and log in with one of the mock accounts above." -ForegroundColor DarkGray
        & py -3.11 -m streamlit run src/ui/streamlit_app.py
    }
    2 {
        Write-Host ""
        Write-Host "Launching CLI demo..." -ForegroundColor Green
        & py -3.11 scripts/demo_cli.py
    }
    3 {
        Write-Host ""
        Write-Host "Launching FastAPI server..." -ForegroundColor Green
        & py -3.11 -m uvicorn app.main:app --app-dir src --reload
    }
}
